### ISSUE TITLE
Server internal exception with Door Flipper and C2ME

### ISSUE THREAD

**Issue by FibreTTP** [AmyMialeeMods/half-doors#14]
###### This issue is based on the one submitted to C2ME | https://github.com/RelativityMC/C2ME-fabric/issues/196

**Describe the bug**
Using the Door Flipper with [C2ME](https://www.curseforge.com/minecraft/mc-mods/c2me-fabric/) (Concurrent Chunk Management Engine) on the server (Fabric OR Quilt) will disconnect the client from the server. It does not crash the server nor the client's game.

Other players on the server will not be disconnected.

This also occurs in a singleplayer world.

**To Reproduce**
1. Equip Door Flipper in Trinket slot (right-clicking will do this)
2. Press keybind (default: 'r') to use the Door Flipper.
3. Client is disconnected from the server and will get this message on the screen:
![image](https://user-images.githubusercontent.com/120446961/216589943-19b7c360-a3e7-47ae-a5fd-09300a768263.png)
Also appears in server log.

Even when the issue happens on a singleplayer world, it will still take you back to the server list.

**Expected behavior**

When you use the Door Flipper, a sound plays and a tiny half-door seems to be shot out of it.

To be honest, I have no idea what that item is actually supposed to be. It just does this:

https://user-images.githubusercontent.com/120446961/216592105-4ff9b919-4b7b-4d52-925d-ab10b1d1060f.mp4

someone please tell me what it does

**Runtime info (please complete the following information):**
 - OS: Windows 10
 - Minecraft version: 1.19.2
 - Mod version: Halfdoors 1.3.9

**Crash reports / logs**
Server log: https://gist.github.com/FibreTTP/2a3ba58aa33e8b170ff0355ff98c1da3

Client log (nothing interesting here): https://gist.github.com/FibreTTP/b54dcd02379ae02b4f1f766acec10d9a

**Other mods**
 - Fabric API (0.73.2)
 - [C2ME](https://www.curseforge.com/minecraft/mc-mods/c2me-fabric/) (1.3.9 - 1.19.x) | [GitHub](https://github.com/RelativityMC/C2ME-fabric)
 - [Trinkets](https://www.curseforge.com/minecraft/mc-mods/trinkets) (3.4.2) | Halfdoors depends on Trinkets. | [GitHub](https://github.com/emilyploszaj/trinkets)

**Checklist**

 - [x] I am using the official version of the mod. 
 - [x] I searched for similar open issues and could not find an existing bug report on this. 
 
---

Apparently, this is caused by Halfdoors doing "something it absolutely shouldn't."

**Comment by AmyMialee** [comment]
Item isn't in the current version of the mod, might be added in a theoretical addon mod at some point.
