### ISSUE TITLE
Permission for Forge ports?

### ISSUE THREAD

**Issue by Kitteh6660** [AmyMialeeMods/half-doors#16]
Hello. I would like to ask a question, and I'm wondering.

What's your stance on allowing the mod to be ported to Forge? It looks like a rather simple mod and the idea of 1 block tall door that opens and swings horizontally is cool.

**Comment by AmyMialee** [comment]
You could make another mod with it's own art/name/code that does the same idea, but not a port of this one.
Using the same name implies they're the same mod and are endorsed which I can't really do at the time being.
