### ISSUE TITLE
[Feature Idea] Door Shield

### ISSUE THREAD

**Issue by AmyMialee** [AmyMialeeMods/half-doors#7]
Some kind of door shield that closes when holding right click and is otherwise open.

Ideally when you let go of right click it should try to reflect projectiles within a short distance, like a form of parry by opening the door at the right time.

Should be less annoying than vanilla shields, probably going on a cooldown when hit by any attack that isn't parried.

**Comment by AmyMialee** [comment]
Also ideally just don't make it require durability, it'd be more fun without it.

**Comment by AmyMialee** [comment]
The cooldown on hit should be longer than it takes for a skeleton to shoot you, so you can only block every second arrow unless your parries are on point.

**Comment by williambl** [comment]
i'd like to do this

**Comment by AmyMialee** [comment]
Might be in a theoretical addon mod.
